// STORY-054 G3b — offline-aware appointment repository wrappers.
//
// Mirror of `clientsCached.ts` for the `appointments` table. Same
// SWR pattern, same conflict-detection via `updated_at`, same
// optimistic UI. No tag-assignment wrinkle here — appointments
// don't have a junction table on the cached scope.
//
// Service catalog is NOT cached (decision #1 from G0). Appointments
// store a JSONB `services` array inline; we cache that as part of
// the row. So an appointment row read from IDB shows the prices
// frozen at the time of last sync. That's correct semantics: the
// appointment's services are bound to the appointment row, not to
// the live catalog.
//
// `master_id` is text (legacy slug, not uuid — STORY-039b will
// migrate). Cached as-is; the wrapper does not interpret it.

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@babun/shared/db/database.types";
import {
  listAppointments as repoListAppointments,
  createAppointment as repoCreateAppointment,
  updateAppointment as repoUpdateAppointment,
  deleteAppointment as repoDeleteAppointment,
} from "@babun/shared/db/repositories/appointments";
import type { Appointment } from "@babun/shared/local/appointments";
import {
  cacheRead,
  cacheUpsert,
  cacheDelete,
  cacheBulkUpsert,
  type CachedAppointment,
} from "@babun/shared/db/cache";
import { isOnline } from "./network";
import { kickReplayer } from "./replayer";
import { enqueueOpAndEmit as enqueueOp } from "./queue-events";
import {
  assertQuotaAvailable,
  QuotaExceededError,
} from "@/lib/quota/check";

type DbSupabase = SupabaseClient<Database>;

// v452 — UUID guard. The Supabase `appointments` table has `id` as
// uuid; sending the legacy local-storage id pattern (`apt-${ts}-rnd`,
// generated by `generateId("apt")`) makes Postgres reject the whole
// statement with «invalid input syntax for type uuid». That's how the
// PersonalEventSheet's create+delete cycle was poisoning the sync
// queue with unreplayable ops.
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const isUuid = (s: string): boolean => UUID_RE.test(s);

// ─── Read ─────────────────────────────────────────────────────────

export async function listAppointments(
  supabase: DbSupabase,
  tenantId: string,
): Promise<Appointment[]> {
  const cached = await safeCacheReadAppointments(tenantId);
  if (cached.length > 0) {
    void revalidateAppointments(supabase, tenantId);
    return cached.map(rowToAppointment);
  }
  const fresh = await repoListAppointments(supabase, tenantId);
  await refreshCacheFromSupabase(supabase, tenantId).catch(() => {});
  return fresh;
}

async function revalidateAppointments(
  supabase: DbSupabase,
  tenantId: string,
): Promise<void> {
  try {
    await refreshCacheFromSupabase(supabase, tenantId);
  } catch {
    // ignore — cached list already returned
  }
}

async function refreshCacheFromSupabase(
  supabase: DbSupabase,
  tenantId: string,
): Promise<void> {
  const { data, error } = await supabase
    .from("appointments")
    .select("*")
    .eq("tenant_id", tenantId);
  if (error) throw new Error(`refreshAppointments: ${error.message}`);
  await cacheBulkUpsert(
    "appointments",
    (data ?? []) as CachedAppointment[],
  );
}

function rowToAppointment(r: CachedAppointment): Appointment {
  return {
    id: r.id,
    date: r.date,
    time_start: r.time_start,
    time_end: r.time_end,
    client_id: r.client_id,
    location_id: r.location_id,
    team_id: r.team_id,
    master_id: r.master_id,
    service_ids: asStringArray(r.service_ids),
    total_amount: r.total_amount,
    custom_total: r.custom_total,
    discount_amount: r.discount_amount,
    expenses: asArray(r.expenses) as Appointment["expenses"],
    service_price_overrides: asRecord(r.service_price_overrides) as Record<string, number>,
    color_override: r.color_override,
    prepaid_amount: r.prepaid_amount,
    payments: asArray(r.payments) as Appointment["payments"],
    payment: (r.payment ?? null) as Appointment["payment"],
    services: asArray(r.services) as Appointment["services"],
    kind: (r.kind ?? "work") as Appointment["kind"],
    status: (r.status ?? "scheduled") as Appointment["status"],
    comment: r.comment ?? "",
    address: r.address ?? "",
    address_note: r.address_note ?? "",
    address_lat: r.address_lat,
    address_lng: r.address_lng,
    cancel_reason: r.cancel_reason ?? null,
    source: (r.source ?? null) as Appointment["source"],
    is_online_booking: r.is_online_booking,
    consent_given: r.consent_given,
    reminder_enabled: r.reminder_enabled,
    reminder_offsets: asArray(r.reminder_offsets) as Appointment["reminder_offsets"],
    reminder_template: r.reminder_template ?? "",
    global_discount: (r.global_discount ?? null) as Appointment["global_discount"],
    total_duration: r.total_duration,
    payment_status: (r.payment_status ?? "unpaid") as Appointment["payment_status"],
    payment_method: (r.payment_method ?? undefined) as Appointment["payment_method"],
    paid_amount: r.paid_amount ?? 0,
    photos: [], // not cached — fetched separately by photo viewer
    created_at: r.created_at,
    updated_at: r.updated_at,
  };
}

function asArray<T = unknown>(v: unknown): T[] {
  return Array.isArray(v) ? (v as T[]) : [];
}
function asRecord(v: unknown): Record<string, unknown> {
  return v && typeof v === "object" && !Array.isArray(v)
    ? (v as Record<string, unknown>)
    : {};
}
function asStringArray(v: unknown): string[] {
  return Array.isArray(v)
    ? v.filter((x): x is string => typeof x === "string")
    : [];
}

// ─── Write ────────────────────────────────────────────────────────

export async function createAppointment(
  supabase: DbSupabase,
  input: Appointment,
  tenantId: string,
): Promise<Appointment> {
  const id =
    input.id ||
    (typeof crypto !== "undefined" ? crypto.randomUUID() : `tmp_${Date.now()}`);
  const nowIso = new Date().toISOString();
  const optimisticRow = makeOptimisticRow(input, tenantId, id, nowIso);
  await cacheUpsert("appointments", optimisticRow);

  // STORY-052 G4 — same online-only quota gate as clientsCached.
  // Offline replays go through the standard repo path; future
  // STORY-052b BEFORE INSERT trigger handles the bypass case.
  if (isOnline()) {
    try {
      await assertQuotaAvailable(supabase, tenantId, "appointments_month");
    } catch (err) {
      if (err instanceof QuotaExceededError) {
        await cacheDelete("appointments", id);
      }
      throw err;
    }
    try {
      const created = await repoCreateAppointment(
        supabase,
        { ...input, id },
        tenantId,
      );
      // v452 — rebind cache from the optimistic local-id row to the
      // canonical UUID Supabase allocated. Without this, the cache
      // accumulates orphan "apt-XXX" rows alongside the real ones,
      // and a later delete on the orphan poisons the sync queue.
      if (created.id !== id) {
        try {
          await cacheDelete("appointments", id);
        } catch {
          /* ignore — cache may not have stored the optimistic row */
        }
      }
      await refetchAndCacheOne(supabase, created.id, tenantId);
      return created;
    } catch (err) {
      void err;
      await enqueueOp({
        table: "appointments",
        op: "insert",
        row_id: id,
        payload: optimisticRow as unknown as Record<string, unknown>,
        expected_updated_at: null,
      });
      void kickReplayer({ supabase });
      return { ...input, id };
    }
  }

  await enqueueOp({
    table: "appointments",
    op: "insert",
    row_id: id,
    payload: optimisticRow as unknown as Record<string, unknown>,
    expected_updated_at: null,
  });
  return { ...input, id };
}

export async function updateAppointment(
  supabase: DbSupabase,
  id: string,
  patch: Partial<Appointment>,
  tenantId: string,
): Promise<Appointment> {
  const existing = await readCachedAppointment(id);
  const expectedUpdatedAt = existing?.updated_at ?? null;

  if (existing) {
    const merged: CachedAppointment = {
      ...existing,
      ...patchToRow(patch),
      updated_at: new Date().toISOString(),
    };
    await cacheUpsert("appointments", merged);
  }

  // v452 — non-UUID ids never made it to Supabase. Skip the network
  // + queue path; the cache write above is the full story.
  if (!isUuid(id)) {
    return { ...(existing as unknown as Appointment), ...patch, id };
  }

  if (isOnline()) {
    try {
      const updated = await repoUpdateAppointment(
        supabase,
        id,
        patch,
        tenantId,
      );
      await refetchAndCacheOne(supabase, id, tenantId);
      return updated;
    } catch (err) {
      void err;
      await enqueueOp({
        table: "appointments",
        op: "update",
        row_id: id,
        payload: patchToRow(patch) as Record<string, unknown>,
        expected_updated_at: expectedUpdatedAt,
      });
      void kickReplayer({ supabase });
      return { ...(existing as unknown as Appointment), ...patch, id };
    }
  }

  await enqueueOp({
    table: "appointments",
    op: "update",
    row_id: id,
    payload: patchToRow(patch) as Record<string, unknown>,
    expected_updated_at: expectedUpdatedAt,
  });
  return { ...(existing as unknown as Appointment), ...patch, id };
}

export async function deleteAppointment(
  supabase: DbSupabase,
  id: string,
  tenantId: string,
): Promise<void> {
  await cacheDelete("appointments", id);

  // v452 — non-UUID ids are local orphans (the row never made it to
  // Supabase because an earlier insert failed). Skip the network +
  // queue entirely so we don't keep re-enqueueing dead ops.
  if (!isUuid(id)) return;

  if (isOnline()) {
    try {
      await repoDeleteAppointment(supabase, id, tenantId);
      return;
    } catch {
      // fall through to queue
    }
  }
  await enqueueOp({
    table: "appointments",
    op: "delete",
    row_id: id,
    payload: { id, tenant_id: tenantId },
    expected_updated_at: null,
  });
  if (isOnline()) void kickReplayer({ supabase });
}

// ─── Helpers ──────────────────────────────────────────────────────

async function safeCacheReadAppointments(
  tenantId: string,
): Promise<CachedAppointment[]> {
  try {
    return await cacheRead<CachedAppointment>("appointments", tenantId);
  } catch {
    return [];
  }
}

async function readCachedAppointment(
  id: string,
): Promise<CachedAppointment | null> {
  try {
    const { getCache } = await import("@babun/shared/db/cache");
    const db = await getCache();
    const row = await db.get("appointments", id);
    return row ?? null;
  } catch {
    return null;
  }
}

async function refetchAndCacheOne(
  supabase: DbSupabase,
  id: string,
  tenantId: string,
): Promise<void> {
  const { data, error } = await supabase
    .from("appointments")
    .select("*")
    .eq("id", id)
    .eq("tenant_id", tenantId)
    .maybeSingle();
  if (error || !data) return;
  await cacheUpsert("appointments", data as CachedAppointment);
}

function makeOptimisticRow(
  input: Appointment,
  tenantId: string,
  id: string,
  nowIso: string,
): CachedAppointment {
  return {
    id,
    tenant_id: tenantId,
    client_id: input.client_id ?? null,
    team_id: input.team_id ?? null,
    master_id: input.master_id ?? null,
    location_id: input.location_id ?? null,
    date: input.date,
    time_start: input.time_start,
    time_end: input.time_end,
    kind: input.kind ?? "work",
    status: input.status ?? "scheduled",
    total_amount: input.total_amount ?? 0,
    custom_total: input.custom_total ?? false,
    discount_amount: input.discount_amount ?? 0,
    prepaid_amount: input.prepaid_amount ?? 0,
    comment: input.comment ?? "",
    address: input.address ?? "",
    address_note: input.address_note ?? "",
    address_lat: input.address_lat ?? null,
    address_lng: input.address_lng ?? null,
    cancel_reason: input.cancel_reason ?? null,
    source: input.source ?? null,
    is_online_booking: input.is_online_booking ?? false,
    consent_given: input.consent_given ?? true,
    color_override: input.color_override ?? null,
    reminder_enabled: input.reminder_enabled ?? false,
    reminder_offsets: (input.reminder_offsets ?? []) as unknown as CachedAppointment["reminder_offsets"],
    reminder_template: input.reminder_template ?? "",
    service_ids: (input.service_ids ?? []) as unknown as CachedAppointment["service_ids"],
    services: (input.services ?? []) as unknown as CachedAppointment["services"],
    service_price_overrides: (input.service_price_overrides ?? {}) as unknown as CachedAppointment["service_price_overrides"],
    expenses: (input.expenses ?? []) as unknown as CachedAppointment["expenses"],
    payments: (input.payments ?? []) as unknown as CachedAppointment["payments"],
    payment: (input.payment ?? null) as CachedAppointment["payment"],
    global_discount: (input.global_discount ?? null) as CachedAppointment["global_discount"],
    total_duration: input.total_duration ?? 0,
    payment_status: input.payment_status ?? "unpaid",
    payment_method: input.payment_method ?? null,
    paid_amount: input.paid_amount ?? 0,
    // STORY-055 — created_by is filled server-side by the BEFORE
    // INSERT trigger; the optimistic cache row carries null and gets
    // rewritten on refetchAndCacheOne after the real insert.
    created_by: null,
    created_at: input.created_at ?? nowIso,
    updated_at: nowIso,
    // Event-mode fields (personal calendar). All have safe defaults so
    // a non-event appointment slots in as a regular work record.
    event_all_day: input.event_all_day ?? false,
    event_notes: input.event_notes ?? "",
    event_url: input.event_url ?? "",
    event_push_enabled: input.event_push_enabled ?? false,
    event_push_offsets: (input.event_push_offsets ?? []) as unknown as CachedAppointment["event_push_offsets"],
    event_push_at: input.event_push_at ?? null,
    event_repeat: (input.event_repeat ?? { kind: "none" }) as unknown as CachedAppointment["event_repeat"],
  };
}

function patchToRow(patch: Partial<Appointment>): Partial<CachedAppointment> {
  const out: Partial<CachedAppointment> = {};
  if (patch.client_id !== undefined) out.client_id = patch.client_id;
  if (patch.team_id !== undefined) out.team_id = patch.team_id;
  if (patch.master_id !== undefined) out.master_id = patch.master_id ?? null;
  if (patch.location_id !== undefined) out.location_id = patch.location_id;
  if (patch.date !== undefined) out.date = patch.date;
  if (patch.time_start !== undefined) out.time_start = patch.time_start;
  if (patch.time_end !== undefined) out.time_end = patch.time_end;
  if (patch.kind !== undefined) out.kind = patch.kind;
  if (patch.status !== undefined) out.status = patch.status;
  if (patch.total_amount !== undefined) out.total_amount = patch.total_amount;
  if (patch.custom_total !== undefined) out.custom_total = patch.custom_total;
  if (patch.discount_amount !== undefined) out.discount_amount = patch.discount_amount;
  if (patch.prepaid_amount !== undefined) out.prepaid_amount = patch.prepaid_amount;
  if (patch.comment !== undefined) out.comment = patch.comment;
  if (patch.address !== undefined) out.address = patch.address;
  if (patch.address_note !== undefined) out.address_note = patch.address_note;
  if (patch.address_lat !== undefined) out.address_lat = patch.address_lat;
  if (patch.address_lng !== undefined) out.address_lng = patch.address_lng;
  if (patch.cancel_reason !== undefined) out.cancel_reason = patch.cancel_reason;
  if (patch.source !== undefined) out.source = patch.source;
  if (patch.is_online_booking !== undefined) out.is_online_booking = patch.is_online_booking;
  if (patch.consent_given !== undefined) out.consent_given = patch.consent_given;
  if (patch.color_override !== undefined) out.color_override = patch.color_override;
  if (patch.reminder_enabled !== undefined) out.reminder_enabled = patch.reminder_enabled;
  if (patch.reminder_offsets !== undefined) out.reminder_offsets = patch.reminder_offsets as unknown as CachedAppointment["reminder_offsets"];
  if (patch.reminder_template !== undefined) out.reminder_template = patch.reminder_template;
  if (patch.service_ids !== undefined) out.service_ids = patch.service_ids as unknown as CachedAppointment["service_ids"];
  if (patch.services !== undefined) out.services = patch.services as unknown as CachedAppointment["services"];
  if (patch.service_price_overrides !== undefined) out.service_price_overrides = patch.service_price_overrides as unknown as CachedAppointment["service_price_overrides"];
  if (patch.expenses !== undefined) out.expenses = patch.expenses as unknown as CachedAppointment["expenses"];
  if (patch.payments !== undefined) out.payments = patch.payments as unknown as CachedAppointment["payments"];
  if (patch.payment !== undefined) out.payment = patch.payment as CachedAppointment["payment"];
  if (patch.global_discount !== undefined) out.global_discount = patch.global_discount as CachedAppointment["global_discount"];
  if (patch.total_duration !== undefined) out.total_duration = patch.total_duration;
  if (patch.payment_status !== undefined) out.payment_status = patch.payment_status;
  if (patch.payment_method !== undefined) out.payment_method = patch.payment_method ?? null;
  if (patch.paid_amount !== undefined) out.paid_amount = patch.paid_amount;
  return out;
}
