// finance_transactions repository — the new /finances ledger.
//
// One row per money movement. Auto-rows are generated by the
// sync_appointment_finance trigger when an appointment goes
// completed+paid; manual rows come from +Доход / +Расход / +Перевод
// forms. Transfers are stored as a pair of rows sharing the same
// transfer_group_id (one negative on the source account, one positive
// on the destination). Refunds carry refund_of_id pointing at the
// original income.

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../database.types";
import type {
  FinanceTransaction,
  TransactionType,
  TransactionSource,
  PaymentMethod,
} from "../../local/finance/transaction";

type DbSupabase = SupabaseClient<Database>;
type Row = Database["public"]["Tables"]["finance_transactions"]["Row"];
type Insert = Database["public"]["Tables"]["finance_transactions"]["Insert"];

function rowToTx(r: Row): FinanceTransaction {
  return {
    id: r.id,
    tenant_id: r.tenant_id,
    type: r.type as TransactionType,
    amount: Number(r.amount ?? 0),
    currency: r.currency,
    category_id: r.category_id,
    account_id: r.account_id,
    appointment_id: r.appointment_id,
    client_id: r.client_id,
    team_id: r.team_id,
    master_id: r.master_id,
    payment_method: (r.payment_method ?? null) as PaymentMethod | null,
    notes: r.notes,
    occurred_on: r.occurred_on,
    receipt_url: r.receipt_url,
    transfer_group_id: r.transfer_group_id,
    invoice_id: r.invoice_id,
    refund_of_id: r.refund_of_id,
    source: r.source as TransactionSource,
    created_at: r.created_at,
    updated_at: r.updated_at,
    created_by: r.created_by,
  };
}

export interface ListRangeOptions {
  brigadeIds?: string[];
  accountIds?: string[];
  categoryIds?: string[];
  clientIds?: string[];
  types?: TransactionType[];
}

/**
 * Range is inclusive on both ends. Dates are YYYY-MM-DD strings,
 * compared against `occurred_on`.
 */
export async function listTransactionsForRange(
  supabase: DbSupabase,
  tenantId: string,
  fromDate: string,
  toDate: string,
  opts: ListRangeOptions = {},
): Promise<FinanceTransaction[]> {
  let q = supabase
    .from("finance_transactions")
    .select("*")
    .eq("tenant_id", tenantId)
    .gte("occurred_on", fromDate)
    .lte("occurred_on", toDate);
  if (opts.brigadeIds && opts.brigadeIds.length > 0) q = q.in("team_id", opts.brigadeIds);
  if (opts.accountIds && opts.accountIds.length > 0) q = q.in("account_id", opts.accountIds);
  if (opts.categoryIds && opts.categoryIds.length > 0) q = q.in("category_id", opts.categoryIds);
  if (opts.clientIds && opts.clientIds.length > 0) q = q.in("client_id", opts.clientIds);
  if (opts.types && opts.types.length > 0) q = q.in("type", opts.types);
  const { data, error } = await q
    .order("occurred_on", { ascending: false })
    .order("created_at", { ascending: false });
  if (error) throw new Error(`listTransactionsForRange: ${error.message}`);
  return ((data ?? []) as Row[]).map(rowToTx);
}

export interface TransactionDraft {
  type: Exclude<TransactionType, "transfer">; // transfers use a separate helper
  amount: number;
  category_id?: string | null;
  account_id?: string | null;
  appointment_id?: string | null;
  client_id?: string | null;
  team_id?: string | null;
  master_id?: string | null;
  payment_method?: PaymentMethod | null;
  notes?: string | null;
  occurred_on?: string;
  receipt_url?: string | null;
  invoice_id?: string | null;
  refund_of_id?: string | null;
}

export async function insertTransaction(
  supabase: DbSupabase,
  tenantId: string,
  draft: TransactionDraft,
): Promise<FinanceTransaction> {
  const insert: Insert = {
    tenant_id: tenantId,
    type: draft.type,
    amount: draft.amount,
    category_id: draft.category_id ?? null,
    account_id: draft.account_id ?? null,
    appointment_id: draft.appointment_id ?? null,
    client_id: draft.client_id ?? null,
    team_id: draft.team_id ?? null,
    master_id: draft.master_id ?? null,
    payment_method: draft.payment_method ?? null,
    notes: draft.notes ?? null,
    occurred_on: draft.occurred_on ?? new Date().toISOString().slice(0, 10),
    receipt_url: draft.receipt_url ?? null,
    invoice_id: draft.invoice_id ?? null,
    refund_of_id: draft.refund_of_id ?? null,
    source: "manual",
  };
  const { data, error } = await supabase
    .from("finance_transactions")
    .insert(insert)
    .select("*")
    .single();
  if (error || !data) throw new Error(`insertTransaction: ${error?.message}`);
  return rowToTx(data as Row);
}

export async function updateTransaction(
  supabase: DbSupabase,
  id: string,
  patch: Partial<TransactionDraft>,
): Promise<void> {
  const update: Partial<Database["public"]["Tables"]["finance_transactions"]["Update"]> = {};
  if (patch.amount !== undefined) update.amount = patch.amount;
  if (patch.category_id !== undefined) update.category_id = patch.category_id;
  if (patch.account_id !== undefined) update.account_id = patch.account_id;
  if (patch.client_id !== undefined) update.client_id = patch.client_id;
  if (patch.team_id !== undefined) update.team_id = patch.team_id;
  if (patch.master_id !== undefined) update.master_id = patch.master_id;
  if (patch.payment_method !== undefined) update.payment_method = patch.payment_method;
  if (patch.notes !== undefined) update.notes = patch.notes;
  if (patch.occurred_on !== undefined) update.occurred_on = patch.occurred_on;
  if (patch.receipt_url !== undefined) update.receipt_url = patch.receipt_url;
  const { error } = await supabase.from("finance_transactions").update(update).eq("id", id);
  if (error) throw new Error(`updateTransaction: ${error.message}`);
}

export async function deleteTransaction(
  supabase: DbSupabase,
  id: string,
): Promise<void> {
  const { error } = await supabase.from("finance_transactions").delete().eq("id", id);
  if (error) throw new Error(`deleteTransaction: ${error.message}`);
}

export interface TransferDraft {
  from_account_id: string;
  to_account_id: string;
  amount: number; // positive
  occurred_on?: string;
  notes?: string | null;
  brigade_id?: string | null;
}

/**
 * Create a pair of `transfer`-type rows sharing the same
 * `transfer_group_id`. The source row is negative, the destination is
 * positive — so summing the pair across the tenant is zero. The pair
 * lives or dies together: if either insert fails, we attempt to roll
 * back the other so the ledger never carries a half-transfer.
 */
export async function createTransfer(
  supabase: DbSupabase,
  tenantId: string,
  t: TransferDraft,
): Promise<{ source: FinanceTransaction; destination: FinanceTransaction }> {
  const groupId =
    typeof crypto !== "undefined" && "randomUUID" in crypto
      ? crypto.randomUUID()
      : `tg-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const occurredOn = t.occurred_on ?? new Date().toISOString().slice(0, 10);
  const baseNotes = t.notes ?? null;

  const sourceInsert: Insert = {
    tenant_id: tenantId,
    type: "transfer",
    amount: -Math.abs(t.amount),
    account_id: t.from_account_id,
    team_id: t.brigade_id ?? null,
    notes: baseNotes,
    occurred_on: occurredOn,
    transfer_group_id: groupId,
    source: "manual",
  };
  const destInsert: Insert = {
    tenant_id: tenantId,
    type: "transfer",
    amount: Math.abs(t.amount),
    account_id: t.to_account_id,
    team_id: t.brigade_id ?? null,
    notes: baseNotes,
    occurred_on: occurredOn,
    transfer_group_id: groupId,
    source: "manual",
  };

  const { data: src, error: srcErr } = await supabase
    .from("finance_transactions")
    .insert(sourceInsert)
    .select("*")
    .single();
  if (srcErr || !src) throw new Error(`createTransfer (source): ${srcErr?.message}`);

  const { data: dst, error: dstErr } = await supabase
    .from("finance_transactions")
    .insert(destInsert)
    .select("*")
    .single();
  if (dstErr || !dst) {
    // best-effort rollback so the ledger never carries a half-transfer
    await supabase.from("finance_transactions").delete().eq("id", src.id);
    throw new Error(`createTransfer (destination): ${dstErr?.message}`);
  }
  return { source: rowToTx(src as Row), destination: rowToTx(dst as Row) };
}

/**
 * Cancel a transfer pair atomically. Looks up both rows by group id
 * and deletes them in one round-trip.
 */
export async function deleteTransfer(
  supabase: DbSupabase,
  groupId: string,
): Promise<void> {
  const { error } = await supabase
    .from("finance_transactions")
    .delete()
    .eq("transfer_group_id", groupId);
  if (error) throw new Error(`deleteTransfer: ${error.message}`);
}
